# Generated by Django 4.2.7 on 2023-11-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_record_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
